name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install logging
        pip install typing
        pip install pathlib
        pip install numpy
        pip install scipy
        pip install polars
        pip install matplotlib
        pip install seaborn
        pip install tqdm
        pip install stochastic
        pip install pytest
    - name: Running tests with pytest
      run: |
        pytest
  
